import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // ---------------------------------------------------------------------
    // Vendored shadcn/ui primitives.
    // ---------------------------------------------------------------------
    // These files are generated by `npx shadcn add`, not written here, and the
    // two rules below fire on shapes that are upstream's documented idiom. The
    // obvious "fix" in both cases makes the codebase worse, so the rules are
    // scoped off for this directory rather than the files being edited.
    //
    // Exactly two rules, not a blanket off: anything else that fires in here is
    // still a finding worth seeing, including in the handful of these files that
    // have been locally adjusted.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      // Fires on badge/button/toggle (`buttonVariants` etc.), form
      // (`useFormField`), navigation-menu (`navigationMenuTriggerStyle`),
      // sidebar (`useSidebar`) and sonner (`toast`) — every one a cva variants
      // object or hook that upstream exports from the same module as its
      // component. Splitting them into sibling files would satisfy the rule and
      // break the public API every consumer already imports
      // (`import { Button, buttonVariants } from "@/components/ui/button"`),
      // and the next `shadcn add` would regenerate the merged file anyway and
      // silently undo the split. The actual cost of leaving it is that editing
      // one of these modules does a full reload instead of a hot swap in dev.
      "react-refresh/only-export-components": "off",
      // command.tsx `interface CommandDialogProps extends DialogProps {}` and
      // textarea.tsx `interface TextareaProps extends React.TextareaHTMLAttributes<…> {}`.
      // The empty body is the point: it gives the props a name consumers can
      // import and a declaration other code can merge into. Collapsing either to
      // a type alias silences the rule and removes both of those properties.
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },
);
